import { Theme } from "../theme.slint";

export component BackLink inherits Rectangle {
    in property <string> text: @tr("Back");
    in property <image> prefix-icon: @image-url("../assets/icons/chevron-left.svg");
    in property <bool> enabled: true;

    private property <length> icon-width: Theme.typography.label.size + 4px;

    callback clicked();

    touch := TouchArea {
        enabled: root.enabled;
        mouse-cursor: root.enabled ? pointer : not-allowed;
        clicked => { root.clicked(); }
    }

    HorizontalLayout {
        cross-axis-alignment: center;
        spacing: -5px;

        Rectangle {
            width: icon-width;
            height: icon-width;
            clip: true;

            Image {
                x: -4px; // adjust until the visible chevron is flush left
		        width: icon-width;
                height: icon-width;
                source: root.prefix-icon;
                colorize: !root.enabled ? Theme.content-disabled
                    : touch.pressed ? Theme.content-link-pressed
                    : touch.has-hover ? Theme.content-link-hover
                    : Theme.content-link;
            }
        }

        Text {
            text: root.text;
            font-size: Theme.typography.supporting.size;
            font-weight: Theme.typography.supporting.weight;
            color: !root.enabled ? Theme.content-disabled
                : touch.pressed ? Theme.content-link-pressed
                : touch.has-hover ? Theme.content-link-hover
                : Theme.content-secondary;
        }
    }
}
