import { Theme } from "../theme.slint";

export component IconButton inherits Rectangle {
    in property <image> icon;
    in property <color> icon-color: Theme.content-secondary;

    callback clicked();

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.clicked(); }
    }

    background: touch.pressed ? Theme.action-icon-pressed
        : touch.has-hover ? Theme.action-icon-hover
        : Theme.action-icon;
    border-radius: 5px;
    width: 20px;
    height: 20px;

    Image {
        width: parent.width - 4px;
        height: parent.height - 4px;
        source: root.icon;
        colorize: root.icon-color;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

}
