import { ProjectItem } from "../models.slint";
import { Theme } from "../theme.slint";

export component ProjectCard inherits Rectangle {
    in property <ProjectItem> project;

    callback clicked(string);

    height: 38px;
    background: Theme.palette.surface;
    border-radius: Theme.border.radius;
    border-width: Theme.border.width;
    border-color: Theme.palette.border;

    Text {
        text: root.project.name;
        color: Theme.palette.accent;
        font-size: Theme.typography.body-strong.size;
        font-weight: Theme.typography.body-strong.weight;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    TouchArea {
        clicked => { root.clicked(root.project.id); }
    }
}
