import { ProjectItem } from "../models.slint";
import { Theme } from "../theme.slint";

export component ProjectCard inherits Rectangle {
    in property <ProjectItem> project;

    private property <string> timer-tooltip: @tr("Start a timer for {}", root.project.name);

    callback clicked(string);

    touch := TouchArea {
        clicked => { root.clicked(root.project.id); }
    }

    height: 38px;
    background: touch.pressed ? Theme.action-card-pressed
        : touch.has-hover ? Theme.action-card-hover
        : Theme.surface-card;
    border-radius: Theme.border.radius;
    border-width: Theme.border.width;
    border-color: Theme.border-default;

    Text {
        text: root.project.name;
        color: Theme.action-primary;
        font-size: Theme.typography.body-strong.size;
        font-weight: Theme.typography.body-strong.weight;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    Tooltip {
	    text: @markdown("\{root.timer-tooltip}");
	}

}
