import { ScrollView, HorizontalBox } from "std-widgets.slint";

export component ScrollableColumn inherits ScrollView {
    in property <length> spacing: 7px;

	out property <bool> has-scrollbar: self.viewport-height > self.visible-height;

    vertical-stretch: 1;
    vertical-scrollbar-policy: as-needed;

    VerticalLayout {
        x: 0px;
        cross-axis-alignment: stretch;
        spacing: root.spacing;
        width: root.visible-width;
        alignment: start;

        @children
    }
}
