import { ScrollView, HorizontalBox } from "std-widgets.slint";

export component ScrollableColumn inherits ScrollView {
    in property <length> spacing: 7px;
    in property <length> scrollbar-width: 20px;

    vertical-stretch: 1;
    horizontal-scrollbar-policy: always-off;

    out property <bool> has-scrollbar: self.viewport-height > self.visible-height;

    VerticalLayout {
        x: 0px;
        cross-axis-alignment: stretch;
        spacing: root.spacing;
        width: root.width - (root.has-scrollbar ? root.scrollbar-width : 0px);
        alignment: start;

        @children
    }
}
