import { ProjectItem } from "../models.slint";
import { Theme } from "../theme.slint";
import { HorizontalBox } from "std-widgets.slint";

export component SettingsProjectRow inherits Rectangle {
    in property <ProjectItem> project;

    height: 38px;
    border-radius: Theme.border.radius;
    background: Theme.palette.surface;
    border-width: Theme.border.width;
    border-color: Theme.palette.border;

    callback clicked(string);

	HorizontalBox {
		horizontal-stretch: 1;

	    Text {
        text: root.project.name;
	        color: Theme.palette.text;
	        font-size: Theme.typography.body.size;
	        font-weight: Theme.typography.body.weight;
	        vertical-alignment: center;
	        horizontal-alignment: start;
	    }

	    Text {
	        text: "Edit";
	        color: Theme.palette.accent;
	        font-size: Theme.typography.small-label.size;
	        font-weight: Theme.typography.small-label.weight;
	        horizontal-alignment: right;
	        vertical-alignment: center;
	    }
    }

    TouchArea {
        mouse-cursor: pointer;
        clicked => { root.clicked(root.project.id); }
    }
}
