import { ScrollView, VerticalBox } from "std-widgets.slint";
import { ProjectCard } from "../components/project-card.slint";
import { HomeState, TaskItem } from "../models.slint";
import { Theme } from "../theme.slint";
import { ViewHeader } from "../components/typography.slint";

component HomeHeader inherits HorizontalLayout {
    alignment: stretch;
    cross-axis-alignment: center;

    callback open-settings();
    callback open-evaluation();

    ViewHeader {
        text: "What next?";
    }

	HorizontalLayout {
		spacing: 10px;

		Rectangle {
			background: Theme.palette.soft-surface;
			width: 20px;
			height: 20px;

			Image {
	            source: @image-url("../assets/icons/bar-chart.svg");
	            colorize: Theme.palette.secondary-text;
	            width: 18px;
	        }

	        TouchArea {
	            mouse-cursor: pointer;
	            clicked => { open-evaluation(); }
	        }

	        Tooltip {
		        text: @markdown("Evaluation");
		    }
		}

		Rectangle {
			background: Theme.palette.soft-surface;
			width: 20px;
			height: 20px;

	        Image {
	            source: @image-url("../assets/icons/settings.svg");
	            colorize: Theme.palette.secondary-text;
	            width: 18px;
	        }

	        TouchArea {
	            mouse-cursor: pointer;
	            clicked => { open-settings(); }
	        }

	        Tooltip {
		        text: @markdown("Manage projects");
		    }
	    }
    }
}

component LastTaskCard inherits Rectangle {
    in property <TaskItem> task;

    callback clicked();

    min-height: 60px;
    border-radius: 10px;
    background: Theme.palette.accent-surface;

	TouchArea {
		mouse-cursor: pointer;
		clicked => { root.clicked(); }

		VerticalBox {
			spacing: 5px;

			Text {
		        text: "LAST SESSION · TAP TO ADD A NOTE";
		        color: Theme.palette.accent;
		        font-size: Theme.typography.caption.size;
		        font-weight: Theme.typography.caption.weight;
		    }

		    Text {
                text: task.project + " · " + task.duration;
		        color: Theme.palette.text;
		        font-size: Theme.typography.body-strong.size;
		        font-weight: Theme.typography.body-strong.weight;
	        }

	        Text {
		        text: task.note != "" ? task.note : "[No task description]";
		        color: Theme.palette.muted-text;
		        wrap: word-wrap;
		        font-size: Theme.typography.label.size;
		        font-weight: Theme.typography.label.weight;
	        }
	    }

	    Tooltip {
	        text: @markdown("Add a task");
	    }
	}
}

component ProjectList inherits ScrollView {
    in property <HomeState> state;
    out property <bool> has-scrollbar: self.viewport-height > self.visible-height;

    vertical-stretch: 1;
    horizontal-scrollbar-policy: always-off;

    callback clicked(string);

    project-content := VerticalLayout {
        x: 0px;
        cross-axis-alignment: stretch;
        padding-bottom: 16px;
        spacing: 7px;
        width: root.width - (root.has-scrollbar ? 20px : 0px);
        alignment: start;

        for project in root.state.projects: ProjectCard {
            project: project;
            clicked(id) => { root.clicked(id); }
        }
    }
}

component Footer inherits Text {
    height: 16px;
    color: Theme.palette.muted-text;
    font-size: Theme.typography.label.size;
    vertical-alignment: center;
    horizontal-alignment: center;
}

export component HomeView inherits Rectangle {
    in property <HomeState> state;

    callback start-tracking(string);
    callback open-settings();
    callback open-last-task();
    callback open-evaluation();


    content := Rectangle {
        width: root.width;
        height: root.height;

        VerticalLayout {
            padding: 20px;
            spacing: 25px;
            alignment: stretch;

            HomeHeader {
                open-settings => { open-settings(); }
                open-evaluation => { open-evaluation(); }
            }

            if (root.state.last-task.duration != ""): LastTaskCard {
                task: root.state.last-task;
                clicked => { root.open-last-task(); }
            }

            VerticalLayout {
                spacing: 10px;

                Text {
                    text: "Start a timer";
                    color: Theme.palette.accent;
                    font-size: Theme.typography.label.size;
                    font-weight: Theme.typography.label.weight;
                }

                project-list := ProjectList {
                    state: root.state;
                    clicked(project-id) => { root.start-tracking(project-id); }
                }
            }
        }
    }

    if !project-list.has-scrollbar: Footer {
        text: "A quiet place to keep your day moving.";
        y: root.height - self.height - 20px;
    }
}
