import { AppButton } from "../components/app-button.slint";
import { TitleText, BodyText, LabelText, ViewHeader, TextLink } from "../components/typography.slint";
import { Theme } from "../theme.slint";
import { VerticalBox } from "std-widgets.slint";
import { BackLink } from "../components/back-link.slint";

component NoteEditor inherits Rectangle {
    in-out property <string> text;

    border-radius: Theme.border.radius;
    background: Theme.palette.soft-surface;
    border-width: Theme.border.width;
    border-color: Theme.palette.soft-border;

	HorizontalLayout {
		padding: 10px;
		input := TextInput {
			height: 60px;
			width: 100%;
			single-line: false;
            wrap: word-wrap;
	        font-size: Theme.typography.body.size;
	        font-weight: Theme.typography.body.weight;
	        text <=> root.text;
		}
    }

	if root.text == "" && !input.has-focus: Text {
        text: "e.g. prepared the Q4 project brief";
        color: Theme.palette.muted-text;
        font-size: Theme.typography.body.size;
    }
}

export component NoteView inherits Rectangle {
    in property <string> last-session;
    property <string> note-draft: "";

    callback save-note(string);
    callback skip();

    VerticalLayout {
        padding: 20px;
        spacing: 50px;



		VerticalLayout {
			spacing: 20px;

			BackLink {
	            text: "Home";
	        }
			VerticalLayout {
				spacing: 10px;

				TitleText {
		            text: "What did you get done?";
		        }

		        BodyText {
		            text: root.last-session;
		            color: Theme.palette.accent;
		        }
			}
        }

        VerticalLayout {
            spacing: 10px;
            vertical-stretch: 0;

	        LabelText {
	            text: "Add a brief note for your activity log.";
	        }

	        NoteEditor {
	            text <=> root.note-draft;
	        }
        }

        Rectangle {}

		VerticalLayout {
			spacing: 10px;
			vertical-stretch: 0;

	        AppButton {
	            label: "Save note";
	            clicked => { root.save-note(root.note-draft); }
	        }

			VerticalBox {
				cross-axis-alignment: center;

		        TextLink {
		            text: "Skip for now";
		            horizontal-alignment: center;
		            vertical-alignment: top;

			        clicked => { root.skip(); }
		        }
	        }
        }


    }
}
