import { ScrollView } from "std-widgets.slint";
import { AppButton } from "../components/app-button.slint";
import { SettingsProjectRow } from "../components/settings-project-row.slint";
import { ProjectItem } from "../models.slint";
import { Theme } from "../theme.slint";
import { BackLink } from "../components/back-link.slint";
import { TitleText } from "../components/typography.slint";

export component SettingsView inherits Rectangle {
    in property <[ProjectItem]> projects;

    callback open-add-project();
    callback open-rename-project(string);
    callback open-home-view();

    VerticalLayout {
        padding: 20px;
        spacing: 20px;

		BackLink {
			text: @tr("Home");
	        clicked => { open-home-view(); }
	    }

	    TitleText {
	        text: @tr("Project settings");
	    }

        project-list := ScrollView {
	        vertical-stretch: 1;
	        horizontal-scrollbar-policy: always-off;

			private property <bool> has-scrollbar: self.viewport-height > self.visible-height;

	        VerticalLayout {
	            x: 0px;
	            cross-axis-alignment: stretch;
	            spacing: 7px;
                width: project-list.width - (project-list.has-scrollbar ? 20px : 0px);
	            alignment: start;

            for project in root.projects: SettingsProjectRow {
                project: project;
	                clicked(id) => { open-rename-project(id)}
	            }
	        }
	    }

	    AppButton {
	        width: 100%;
	        label: @tr("Add");
	        prefix-icon: @image-url("../assets/icons/add.svg");
        clicked => { root.open-add-project(); }
	    }







    }
}
