import {
    ProjectItem,
    ProjectSettingsState,
    ProjectEditorState,
    ProjectEditorMode,
} from "../models.slint";
import { Theme } from "../theme.slint";
import { ProjectEditor } from "settings/project-editor.slint";
import { ProjectList } from "settings/project-list.slint";

export component SettingsView inherits Rectangle {
    in property <ProjectSettingsState> projects;
    in-out property <ProjectEditorState> editor;

    callback open-home-view();

    function open-project(project: ProjectItem) {
        root.editor = {
            mode: ProjectEditorMode.edit,
            project: project,
            draft-name: project.name
        };
    }

    background: Theme.surface-canvas;

    if root.editor.mode == ProjectEditorMode.list: ProjectList {
        projects: root.projects;
        open-home-view => { root.open-home-view(); }
        open-project(project) => { root.open-project(project)}
        create-project => { root.editor = { mode: ProjectEditorMode.create }; }
    }

    if root.editor.mode != ProjectEditorMode.list: ProjectEditor {
        width: parent.width;
        height: parent.height;
        state <=> root.editor;
    }
}
