import { ScrollView } from "std-widgets.slint";
import { AppButton } from "../components/app-button.slint";
import { SettingsTaskRow } from "../components/settings-task-row.slint";
import { TaskItem } from "../models.slint";
import { Theme } from "../theme.slint";
import { BackLink } from "../components/back-link.slint";

export component SettingsView inherits Rectangle {
    in property <[TaskItem]> tasks;

    callback open-evaluation();
    callback open-add-task();
    callback open-rename-project(string);
    callback open-home-view();

    VerticalLayout {
        padding: 20px;
        spacing: 20px;

		BackLink {
	        clicked => { open-home-view(); }
	    }

	    Text {
	        text: "Projects";
	        color: Theme.palette.text;
	        font-size: Theme.typography.display.size;
	        font-weight: Theme.typography.display.weight;
	        vertical-stretch: 0;
	    }

	    task-list := ScrollView {
	        vertical-stretch: 1;
	        viewport-width: self.visible-width;

	        VerticalLayout {
	            x: 0px;
	            cross-axis-alignment: stretch;
	            spacing: 7px;
	            width: parent.width - 20px;
	            alignment: start;

	            for task in root.tasks: SettingsTaskRow {
	                task: task;
	                clicked(id) => { open-rename-project(id)}
	            }
	        }
	    }

		HorizontalLayout {
			padding-top: 20px;
			spacing: 20px;
			vertical-stretch: 0;

		    AppButton {
		        width: 104px;
		        height: 40px;
		        label: "Add task";
		        prefix-icon: @image-url("../assets/icons/add.svg");
		        primary: false;
		        clicked => { root.open-add-task(); }
		    }
		    AppButton {
		        height: 40px;
		        horizontal-stretch: 1;
		        label: "Evaluation";
		        suffix-icon: @image-url("../assets/icons/chevron-right.svg");
		        primary: true;
		        clicked => { root.open-evaluation(); }
		    }
	    }







    }
}
