import { AppButton, AppButtonIntent, AppButtonVariant, AppButtonSize } from "../components/app-button.slint";
import { TimerDisplay } from "../components/timer-display.slint";
import { Page, TrackingState } from "../models.slint";
import { AppActions } from "../actions.slint";
import { BackLink } from "../components/back-link.slint";
import { Theme } from "../theme.slint";

export component TrackingView inherits Rectangle {
    in property <TrackingState> state;

    VerticalLayout {
        padding: 20px;
        spacing: 10px;

        if (!root.state.secondary-active):  BackLink {
            text: @tr("Home");
            clicked => {
                AppActions.toggle-tracking-pause();
                AppActions.navigate(Page.home);
            }
        }

        VerticalLayout {
            vertical-stretch: 1;
            cross-axis-alignment: center;
            alignment: space-between;

            VerticalLayout {
                Text {
                    text: @tr("Need to step away?");
                    color: Theme.content-primary;
                    font-size: Theme.typography.supporting.size;
                    font-weight: Theme.typography.supporting.weight;
                }
                Text {
                    text: @tr("Going home pauses this task. You can resume it anytime");
                    wrap: word-wrap;
                    font-size: Theme.typography.supporting.size;
                    font-weight: Theme.typography.supporting.weight;
                    color: Theme.content-primary;
                }
            }

            TimerDisplay {
                task: root.state.active-task;
                elapsed: root.state.elapsed;
                paused: root.state.paused;

                pause => { AppActions.toggle-tracking-pause(); }
            }

			VerticalLayout {
				spacing: 10px;

				// End tracking
	            AppButton {
	                width: 232px;
	                size: AppButtonSize.large;
	                label: @tr("End task");
	                intent: root.state.paused ? AppButtonIntent.secondary : AppButtonIntent.primary;

	                clicked => { AppActions.end-tracking(); }
	            }

	            // Pause tracking
	            AppButton {
	                width: 232px;
	                size: AppButtonSize.large;
                label: root.state.paused ? @tr("Resume") : @tr("Pause");
	                label-color: Theme.content-secondary;
	                variant: AppButtonVariant.outline;
	                intent: AppButtonIntent.secondary;

	                clicked => { AppActions.toggle-tracking-pause(); }
	            }
            }
        }
    }
}
