import { AppButton } from "../components/app-button.slint";
import { TimerDisplay } from "../components/timer-display.slint";
import { TrackingState } from "../models.slint";
import { AppActions } from "../actions.slint";

export component TrackingView inherits Rectangle {
    in property <TrackingState> state;

    VerticalLayout {
        padding: 20px;
        spacing: 50px;
        cross-axis-alignment: center;
        alignment: center;

	    TimerDisplay {
	        task: root.state.active-task;
	        elapsed: root.state.elapsed;
	        paused: root.state.paused;

            pause => { AppActions.toggle-tracking-pause(); }
	    }

	    AppButton {
	        width: 232px;
	        height: 50px;
            label: @tr("End task");
	        primary: root.state.paused ? false : true;

            clicked => { AppActions.end-tracking(); }
	    }
	}
}
