#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]

mod tracker;
mod controller;
mod domain;
mod error;
mod language;
#[cfg(all(target_os = "macos", not(test)))]
mod macos_menu;
#[cfg(target_os = "macos")]
use i_slint_backend_winit::{
    Backend,
    winit::platform::macos::WindowAttributesExtMacOS
};
mod persistence;
mod presentation;
mod report;
mod window_state;

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    #[cfg(target_os = "macos")]
    install_native_menu_platform()?;

    // The live preview has no bundled translation catalog, so its visible UI
    // remains English. Keep Rust-projected strings, such as completion dates,
    // in the same language.
    let language = if cfg!(feature = "live-preview") {
        language::Language::English
    } else {
        language::Language::system()
    };
    let ui = AppWindow::new()?;
    window_state::restore(&ui);
    window_state::save_on_close(&ui);

    // Live preview reloads .slint source files and does not include the bundle
    // generated by build.rs.
    #[cfg(not(feature = "live-preview"))]
    slint::select_bundled_translation(language.slint_locale())
        .expect("the selected bundled translation is available");

    let tracker = tracker::Tracker::load_default();
    controller::bind(&ui, tracker, language);

    ui.run()
}

/// Lets Tempo install the complete macOS application menu instead of Slint's
/// default application-only menu.
#[cfg(target_os = "macos")]
fn install_native_menu_platform() -> Result<(), slint::PlatformError> {
    let backend = Backend::builder()
        .with_window_attributes_hook(|attributes| {
            attributes
                .with_transparent(false)
                .with_titlebar_transparent(false)
                .with_fullsize_content_view(false)
                .with_movable_by_window_background(true)
                // .with_titlebar_hidden(true)
        })
        .with_default_menu_bar(false)
        .build()?;
    slint::platform::set_platform(Box::new(backend))
        .map_err(|error| slint::PlatformError::from(error.to_string()))?;
    Ok(())
}
