#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]

mod application;
mod domain;
mod error;
mod language;
mod persistence;
mod presentation;
mod report;
mod ui;

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let language = language::Language::system();
    let ui = AppWindow::new()?;

    // Live preview reloads .slint source files and does not include the bundle
    // generated by build.rs.
    #[cfg(not(feature = "live-preview"))]
    slint::select_bundled_translation(language.slint_locale())
        .expect("the selected bundled translation is available");

    let tracker = application::Tracker::load_default();
    let _timer = ui::bind(&ui, tracker, language);

    ui.run()
}
