export enum Page { home, tracking, note, settings, evaluation, drilldown, project-editor }
export enum Range { day, week, month, year }
export enum StatusKind { success, error }

export struct Status {
    message: string,
    kind: StatusKind,
}

export struct ProjectItem {
    id: string,
    name: string,
    completed: bool,
    archived: bool,
}

export struct TrackingState {
    active-task: string,
    elapsed: string,
    paused: bool,
}

export struct TaskItem {
    project: string,
    note: string,
    duration-seconds: int,
    timestamp: string,
}

export struct EvaluationTaskItem {
    id: string,
    project: string,
    note: string,
    duration-seconds: int,
    completed-label: string,
}

export struct HomeState {
    projects: [ProjectItem],
    last-task: TaskItem,
    has-last-task: bool,
}

export struct ProjectTotalItem {
	id: string,
	project: string,
	duration-seconds: int,
	num_tasks: int,
}

export struct EvaluationState {
    tasks: [EvaluationTaskItem],
    total-seconds: int,
    range: Range,
    project-totals: [ProjectTotalItem]
}

export struct EvaluationTasksState {
    project: string,
    tasks: [EvaluationTaskItem],
    total-seconds: int,
    range: Range,
}

export struct ProjectDialogState {
    rename-mode: bool,
    initial-draft: string,
    project-id: string,
    archived: bool,
}
