export enum Page { home, tracking, note, settings, evaluation }
export enum Range { day, week, month, year }

export struct ProjectItem {
    id: string,
    name: string,
    completed: bool,
}

export struct HomeState {
    projects: [ProjectItem],
    last-task: string,
}

export struct TrackingState {
    active-task: string,
    elapsed: string,
}

export struct TaskItem {
    project: string,
    note: string,
    duration: string,
    timestamp: string,
}

export struct EvaluationState {
    tasks: [TaskItem],
    total: string,
    range: Range,
}

export struct ProjectDialogState {
    open: bool,
    rename-mode: bool,
    initial-draft: string,
}
